### ISSUE TITLE
High Level API for new patching system from Witchy's patching system

### ISSUE THREAD

**Issue by DecDuck** [Sapiens-OSS/hammerstone-framework#33]

**Comment by DecDuck** [comment]
Utility functions to easily expose local variables & functions, that sort of thing

**Comment by WitchyMods** [comment]
I'm not sure I understand. 
It's already part of the patcher.

**Comment by WitchyMods** [comment]
<img width="686" alt="image" src="https://github.com/Sapiens-OSS/hammerstone-framework/assets/43689925/5ece9fa4-cf71-4c17-886a-9fa8f3086301">
